dist: xenial # 16.04 LTS

language: python
python:
  - 3.5.3  # minimum for aiohttp=3 and async-timeout=3
  - 3.5
  - 3.6.0
  - 3.6
  - 3.7-dev
  - nightly

matrix:
  fast_finish: true
  allow_failures:
  - python: 3.7-dev
  - python: nightly
  - python: 3.6  # wtf pytest==3.5.0 TypeError: attrib() got an unexpected keyword argument 'converter' but not in my local env
  include:
  - python: 3.5.3
    env: COCRAWLER_LOGLEVEL=DEBUG
  - python: 3.5.3
    env: PYTHONASYNCIODEBUG=1

git:
  depth: 9999

install: "pip install -r requirements.txt --upgrade-strategy=eager"

script:
  - make test_coverage
after_success:
  coveralls
